name: Create Pull Request to Bump Version

on:
  push:
    tags:
      - '**'

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: ${{vars.RELEASE_BRANCH}}

      - name: Make bump-version.sh executable
        run: chmod +x bump-version.sh

      - name: Run bump-version.sh
        run: ./bump-version.sh $GITHUB_REF_NAME

      - name: Git checkout, add, commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "release/$GITHUB_REF_NAME"
          git add .
          git commit -m "bump version to $GITHUB_REF_NAME"
          git push origin release/$GITHUB_REF_NAME

      - name: Create Release Pull Request
        run: gh pr create -B $RELEASE_BRANCH -H release/$GITHUB_REF_NAME --title "Bump version to $GITHUB_REF_NAME" --body "Created by Github Action"
        env:
          RELEASE_BRANCH: ${{ vars.RELEASE_BRANCH }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
